[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.1", features = [ "derive" ] }
image = { version = "0.25.1", features = ["jpeg", "png"] }
pollster = "0.3.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt", "std", "chrono"] }
wgpu = "0.20.1"
winit = "0.29.15" #temporarily using older version, switch to newer version later
nalgebra = { version = "0.33.0", features = ["serde-serialize"] }
nalgebra-glm = "0.19.0"
tinybitset = "0.0.1"
chrono = "0.4.38"
game = { path = "../game" }
rand = "0.8.5"
shipyard = "0.7.1"
hashbrown = "0.14.5"
noise = "0.9.0"
rayon = "1.10.0"
crossbeam = "0.8.4"
packet = { path  = "../packet" }
packet_derive = { path  = "../packet_derive" }
postcard = "1.0.10"
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }
serde = { version = "1.0.209", features = ["derive"] }
laminar = "0.5.0"
bimap = "0.6.3"
clap = { version = "4.5.17", features = ["derive"] }
rgb = "0.8.50"

[lints]
workspace = true