[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.1", features = [ "derive" ] }
image = { version = "0.25.1", features = ["jpeg", "png"] }
pollster = "0.3.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt", "std", "chrono"] }
wgpu = "0.20.1"
winit = "0.29.15" #temporarily using older version, switch to newer version later
nalgebra = "0.33.0"
nalgebra-glm = "0.19.0"
tinybitset = "0.0.1"
chrono = "0.4.38"
game = { path = "../game" }
rand = "0.8.5"
shipyard = "0.7.1"

[lints.clippy]
unwrap_used = "warn"
