[package]
name = "packet"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.33"
postcard = { version = "1.0.10", features = ["alloc", "use-std"] }
serde = "1.0.209"
thiserror = "1.0.63"

[lints.clippy]
unwrap_used = "warn"
