[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt", "std", "chrono"] }
nalgebra = { version = "0.33.0", features = ["serde-serialize"] }
nalgebra-glm = "0.19.0"
thiserror = "1.0.61"
shipyard = "0.7.1"
serde = { version = "1.0.210", features = ["derive"] }
serde-big-array = "0.5.1"

[lints]
workspace = true
