[package]
name = "uuid-identity"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
uuid = { version = "1.12.0", features = ["v4"] }
rand = "0.9.0-beta.3"
argon2 = "0.5.3"
sha2 = "0.10.8"

[lints]
workspace = true
