[package]
name = "uuid-identity"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
uuid = { version = "1.12.0", features = ["v4"] }
rand = "0.9.0-beta.3"

[lints]
workspace = true