[package]
name = "voxel_game"
version = "0.1.0"
edition = "2021"
authors = ["BlackNinja745 Studios <blackninja745studiosmanagement@gmail.com>"]

[dependencies]

[workspace]
resolver = "2"
members = ["client", "server"]

[workspace.lints.clippy]
unwrap_used = "warn"