[package]
name = "packet_derive"
version = "0.1.0"
description = "Derive macro for protovox engine's packet system"
license.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
syn = "2.0"
quote = "1.0"

[lints]
workspace = true

[lib]
proc-macro = true