[package]
name = "packet_derive"
version = "0.1.0"
edition = "2021"


[dependencies]
syn = "2.0"
quote = "1.0"
packet = { path = "../packet" }

[lints.clippy]
unwrap_used = "warn"

[lib]
proc-macro = true