[package]
name = "splines"
version = "0.1.0"
description = "Custom spline system for protovox engine"
license.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
nalgebra-glm = { workspace = true }

[lints]
workspace = true
