[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt", "std", "chrono"] }
nalgebra = "0.33.0"
nalgebra-glm = "0.19.0"
thiserror = "1.0.61"

[lints.clippy]
unwrap_used = "warn"
